language: node_js
sudo: false
before_install:
  - "export CODECLIMATE_REPO_TOKEN=12bd5a7ba40c47616d610b3bef194eef30b4c8c11d1ea4b929b37672f39f7fda"
install:
  - "npm install"
script:
  - "npm run travis"
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
cache:
  directories:
    - 'node_modules'
